[package]
name = "raytracing"
version = "0.1.0"
edition = "2018"

[[example]]
name = "ppm"
path = "examples/ppm.rs"

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
indicatif = "0.16.2"
num-traits = "0.2.14"
rand = "0.8.4"
rayon = "1.5.1"
